// Copyright © 2017-2023 Esri R&D Center Zurich. All rights reserved.

#pragma once

#include "CoreMinimal.h"
#include "MaterialReplacement.h"
#include "ReplacementDialog.h"

#include "MaterialReplacementDialog.generated.h"

UCLASS(BlueprintType)
class UMaterialReplacement : public UObject
{
	GENERATED_BODY()

public:

	// Non UPROPERTY on purpose since these are transient meshes generated by Vitruvio and are referenced by the VitruvioModule. Keeping references
	// here will lead to World GC cleanup issues on map changes.
	// ReSharper disable once CppUE4ProbableMemoryIssuesWithUObjectsInContainer
	TArray<UStaticMeshComponent*> Components;

	UPROPERTY()
	TSet<UMaterialInterface*> SourceMaterials;

	UPROPERTY()
	FString MaterialIdentifier;

	UPROPERTY()
	UMaterialInterface* ReplacementMaterial;
};

UCLASS(meta = (DisplayName = "Options"))
class UMaterialReplacementDialogOptions : public UObject
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, Category = "Replacements")
	UMaterialReplacementAsset* TargetReplacementAsset;

	UPROPERTY(EditAnywhere, Category = "Replacements")
	TMap<FString, UMaterialReplacement*> MaterialReplacements;
};

class SMaterialReplacementDialogWidget : public SReplacementDialogWidget
{
	TObjectPtr<UMaterialReplacementDialogOptions> ReplacementDialogOptions = nullptr;

	TArray<TSharedPtr<SCheckBox>> IsolateCheckboxes;
	TSharedPtr<SCheckBox> IncludeInstancesCheckBox;
	TSharedPtr<SCheckBox> ApplyToAllVitruvioActorsCheckBox;

public:
	SLATE_BEGIN_ARGS(SMaterialReplacementDialogWidget) {}
	SLATE_ARGUMENT(TSharedPtr<SWindow>, ParentWindow)
	SLATE_ARGUMENT(UVitruvioComponent*, VitruvioComponent)
	SLATE_ARGUMENT(bool, GeneratedWithoutReplacements)
	SLATE_END_ARGS()

	virtual void AddReferencedObjects(FReferenceCollector& Collector) override;

	void Construct(const FArguments& InArgs);

protected:
	virtual FText CreateHeaderText() override;
	virtual TSharedPtr<ISinglePropertyView> CreateTargetReplacementWidget() override;
	virtual void UpdateApplyButtonEnablement() override;
	virtual void OnCreateNewAsset() override;
	virtual void AddDialogOptions(const TSharedPtr<SVerticalBox>& Content) override;
	virtual void OnWindowClosed() override;
	virtual void UpdateReplacementTable() override;
	virtual FReply OnReplacementConfirmed() override;
	virtual FReply OnReplacementCanceled() override;

private:
	void ResetMaterialPreviews();
};

class FMaterialReplacementDialog
{
public:
	template <typename TOnWindowClosed>
	static void OpenDialog(UVitruvioComponent* VitruvioComponent, TOnWindowClosed OnWindowClosed, bool bGeneratedWithoutReplacements)
	{
		FReplacementDialog::OpenDialog<SMaterialReplacementDialogWidget>(VitruvioComponent, OnWindowClosed, bGeneratedWithoutReplacements);
	}
};
